dataset_index : 1           # (0)-PMData, (1)-Custom 
activity_type_index : -1    #activity_types : ['HA_', 'LA_', 'MA_', 'R_', 'ZL_']
activity_value : -1         # -1 : any sleep value
context_level : 0     # (0)-No context 
                      # (1)-Weekends
                      # (2)-Weekends + Holidays 
                      # (3)-Weekends + Holidays + Weather
                      # (4)-Holidays
                      # (5)-Holiday Weekends in same column 
temporal_window : 3         # 3 or 0
min_support : 0.04
min_confidence : 0.8
number_of_bins : 3
type_fun_discritize : 1     # (0)-CUT, (1)-QCUT
zero_label : 1              # (1)-Disabled, (0)-Enabled
print_plot : False
exponential_decay : False